#!/bin/bash

alias abc='yosys-abc'
export OPEN_ROAD=$(pwd)/tools/install/OpenROAD/bin
export YOSYS_ABC=$(pwd)/tools/install/yosys/bin
# export KLAYOUT=/workspace/OpenROAD-flow-scripts/tools/install/usr/bin
export PATH=$PATH:$OPEN_ROAD:$YOSYS_ABC