#!/bin/bash
alias abc='yosys-abc'
export OPEN_ROAD=/workspace/OpenROAD-flow-scripts/tools/install/OpenROAD/bin
export YOSYS=/workspace/OpenROAD-flow-scripts/tools/install/yosys/bin
export KLAYOUT=/workspace/OpenROAD-flow-scripts/tools/install/usr/bin
export PATH=$PATH:$OPEN_ROAD:$YOSYS:$KLAYOUT