/* Generated by Yosys 0.13+15 (git sha1 bc027b2ca, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* hdlname = "\\gcd" *)
(* top =  1  *)
(* src = "./designs/src/gcd/gcd.v:11.1-102.10" *)
module gcd(clk, req_msg, req_rdy, req_val, reset, resp_msg, resp_rdy, resp_val);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.25-6.26" *)
  wire _200_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.28-6.29" *)
  wire _201_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.25-6.26" *)
  wire _202_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.28-6.29" *)
  wire _203_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.25-6.26" *)
  wire _204_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.28-6.29" *)
  wire _205_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.25-6.26" *)
  wire _206_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.28-6.29" *)
  wire _207_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.25-6.26" *)
  wire _208_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.28-6.29" *)
  wire _209_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.25-6.26" *)
  wire _210_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.31-6.32" *)
  wire _211_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.25-6.26" *)
  wire _212_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.28-6.29" *)
  wire _213_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.25-6.26" *)
  wire _214_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.28-6.29" *)
  wire _215_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.28-6.29" *)
  wire _216_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.25-6.26" *)
  wire _217_;
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:10.22-10.24" *)
  wire _218_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:8.26-8.27" *)
  wire _219_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.25-6.26" *)
  wire _220_;
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:10.26-10.28" *)
  wire _221_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:8.29-8.30" *)
  wire _222_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.25-6.26" *)
  wire _223_;
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:10.26-10.28" *)
  wire _224_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:8.29-8.30" *)
  wire _225_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.25-6.26" *)
  wire _226_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:8.29-8.30" *)
  wire _227_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.25-6.26" *)
  wire _228_;
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:10.26-10.28" *)
  wire _229_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:8.29-8.30" *)
  wire _230_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.25-6.26" *)
  wire _231_;
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:10.26-10.28" *)
  wire _232_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:8.29-8.30" *)
  wire _233_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:6.25-6.26" *)
  wire _234_;
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:10.26-10.28" *)
  wire _235_;
  (* force_downto = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:8.29-8.30" *)
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  (* src = "./designs/src/gcd/gcd.v:13.15-13.18" *)
  input clk;
  (* hdlname = "ctrl a_reg_en" *)
  (* src = "./designs/src/gcd/gcd.v:37.37-51.4|./designs/src/gcd/gcd.v:112.24-112.32" *)
  wire \ctrl.a_reg_en ;
  (* hdlname = "ctrl b_reg_en" *)
  (* src = "./designs/src/gcd/gcd.v:37.37-51.4|./designs/src/gcd/gcd.v:114.24-114.32" *)
  wire \ctrl.b_reg_en ;
  (* onehot = 32'd1 *)
  wire [2:0] \ctrl.state.out ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire [15:0] \dpath.a_lt_b$in0 ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire [15:0] \dpath.a_lt_b$in1 ;
  (* hdlname = "dpath a_mux$out" *)
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:442.19-442.28" *)
  wire [15:0] \dpath.a_mux$out ;
  (* hdlname = "dpath b_mux$out" *)
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:461.19-461.28" *)
  wire [15:0] \dpath.b_mux$out ;
  (* src = "./designs/src/gcd/gcd.v:14.24-14.31" *)
  input [31:0] req_msg;
  (* src = "./designs/src/gcd/gcd.v:15.15-15.22" *)
  output req_rdy;
  (* src = "./designs/src/gcd/gcd.v:16.15-16.22" *)
  input req_val;
  (* src = "./designs/src/gcd/gcd.v:17.15-17.20" *)
  input reset;
  (* src = "./designs/src/gcd/gcd.v:18.24-18.32" *)
  output [15:0] resp_msg;
  (* src = "./designs/src/gcd/gcd.v:19.15-19.23" *)
  input resp_rdy;
  (* src = "./designs/src/gcd/gcd.v:20.15-20.23" *)
  output resp_val;
  assign _112_ = \dpath.a_lt_b$in1 [2] & ~(_103_);
  assign _114_ = _105_ & ~(_113_);
  assign _115_ = _114_ | _112_;
  assign \dpath.a_mux$out [2] = _098_ ? req_msg[18] : _115_;
  assign _116_ = \dpath.a_lt_b$in1 [3] & ~(_103_);
  assign _118_ = _117_ ^ _236_;
  assign _119_ = _105_ & ~(_118_);
  assign _120_ = _119_ | _116_;
  assign \dpath.a_mux$out [3] = _098_ ? req_msg[19] : _120_;
  assign _121_ = \dpath.a_lt_b$in1 [4] & ~(_103_);
  assign _123_ = _105_ & ~(_122_);
  assign _124_ = _123_ | _121_;
  assign \dpath.a_mux$out [4] = _098_ ? req_msg[20] : _124_;
  assign _125_ = \dpath.a_lt_b$in1 [5] & ~(_103_);
  assign _127_ = _126_ ^ _233_;
  assign _128_ = _105_ & ~(_127_);
  assign _129_ = _128_ | _125_;
  assign \dpath.a_mux$out [5] = _098_ ? req_msg[21] : _129_;
  assign _130_ = \dpath.a_lt_b$in1 [6] & ~(_103_);
  assign _131_ = ~(_060_ | _050_);
  assign _132_ = _046_ & ~(_131_);
  assign _134_ = _105_ & ~(_133_);
  assign _135_ = _134_ | _130_;
  assign \dpath.a_mux$out [6] = _098_ ? req_msg[22] : _135_;
  assign _136_ = \dpath.a_lt_b$in1 [7] & ~(_103_);
  assign _138_ = _137_ ^ _230_;
  assign _139_ = _105_ & ~(_138_);
  assign _140_ = _139_ | _136_;
  assign \dpath.a_mux$out [7] = _098_ ? req_msg[23] : _140_;
  assign _141_ = \dpath.a_lt_b$in1 [8] & ~(_103_);
  assign _143_ = _105_ & ~(_142_);
  assign _144_ = _143_ | _141_;
  assign \dpath.a_mux$out [8] = _098_ ? req_msg[24] : _144_;
  assign _145_ = \dpath.a_lt_b$in1 [9] & ~(_103_);
  assign _147_ = _146_ ^ _227_;
  assign _148_ = _105_ & ~(_147_);
  assign _149_ = _148_ | _145_;
  assign \dpath.a_mux$out [9] = _098_ ? req_msg[25] : _149_;
  assign _150_ = \dpath.a_lt_b$in1 [10] & ~(_103_);
  assign _151_ = ~(_062_ | _034_);
  assign _152_ = _028_ & ~(_151_);
  assign _154_ = _105_ & ~(_153_);
  assign _155_ = _154_ | _150_;
  assign \dpath.a_mux$out [10] = _098_ ? req_msg[26] : _155_;
  assign _156_ = \dpath.a_lt_b$in1 [11] & ~(_103_);
  assign _158_ = _157_ ^ _225_;
  assign _159_ = _105_ & ~(_158_);
  assign _160_ = _159_ | _156_;
  assign \dpath.a_mux$out [11] = _098_ ? req_msg[27] : _160_;
  assign _161_ = \dpath.a_lt_b$in1 [12] & ~(_103_);
  assign _162_ = _035_ & ~(_062_);
  assign _163_ = _030_ & ~(_162_);
  assign _165_ = _105_ & ~(_164_);
  assign _166_ = _165_ | _161_;
  assign \dpath.a_mux$out [12] = _098_ ? req_msg[28] : _166_;
  assign _167_ = \dpath.a_lt_b$in1 [13] & ~(_103_);
  assign _169_ = _168_ ^ _222_;
  assign _170_ = _105_ & ~(_169_);
  assign _171_ = _170_ | _167_;
  assign \dpath.a_mux$out [13] = _098_ ? req_msg[29] : _171_;
  assign _172_ = \dpath.a_lt_b$in1 [14] & ~(_103_);
  assign _173_ = _016_ & ~(_163_);
  assign _174_ = _012_ & ~(_173_);
  assign _176_ = _105_ & ~(_175_);
  assign _177_ = _176_ | _172_;
  assign \dpath.a_mux$out [14] = _098_ ? req_msg[30] : _177_;
  assign _178_ = \dpath.a_lt_b$in1 [15] & ~(_103_);
  assign resp_msg[15] = _179_ ^ _003_;
  assign _180_ = resp_msg[15] & _105_;
  assign _181_ = _180_ | _178_;
  assign \dpath.a_mux$out [15] = _098_ ? req_msg[31] : _181_;
  assign \ctrl.a_reg_en  = \ctrl.state.out [2] | req_rdy;
  assign \ctrl.b_reg_en  = ~(_101_ & _086_);
  assign resp_msg[3] = ~_118_;
  assign resp_msg[5] = ~_127_;
  assign resp_msg[7] = ~_138_;
  assign resp_msg[9] = ~_147_;
  assign resp_msg[11] = ~_158_;
  assign resp_msg[13] = ~_169_;
  assign _005_ = ~(_004_ | _003_);
  assign _006_ = ~(_005_ | _219_);
  assign _008_ = ~(_007_ | _003_);
  assign _011_ = _222_ & ~(_010_);
  assign _012_ = _009_ & ~(_011_);
  assign _013_ = _008_ & ~(_012_);
  assign _014_ = _006_ & ~(_013_);
  assign _016_ = _222_ & ~(_015_);
  assign _017_ = _016_ & _008_;
  assign _020_ = _225_ & ~(_019_);
  assign _021_ = _018_ & ~(_020_);
  assign _023_ = _225_ & ~(_022_);
  assign _027_ = ~(_026_ | _025_);
  assign _028_ = _024_ & ~(_027_);
  assign _029_ = _023_ & ~(_028_);
  assign _030_ = _021_ & ~(_029_);
  assign _031_ = _017_ & ~(_030_);
  assign _032_ = _014_ & ~(_031_);
  assign _034_ = _033_ | _025_;
  assign _035_ = _023_ & ~(_034_);
  assign _036_ = _035_ & _017_;
  assign _039_ = _230_ & ~(_038_);
  assign _040_ = _037_ & ~(_039_);
  assign _042_ = _230_ & ~(_041_);
  assign _045_ = _233_ & ~(_044_);
  assign _046_ = _043_ & ~(_045_);
  assign _047_ = _042_ & ~(_046_);
  assign _048_ = _040_ & ~(_047_);
  assign _050_ = _049_ | ~(_233_);
  assign _051_ = _042_ & ~(_050_);
  assign _054_ = _236_ & ~(_053_);
  assign _055_ = _052_ & ~(_054_);
  assign _057_ = _236_ & ~(_056_);
  assign _059_ = _057_ & ~(_058_);
  assign _060_ = _055_ & ~(_059_);
  assign _061_ = _051_ & ~(_060_);
  assign _062_ = _048_ & ~(_061_);
  assign _063_ = _036_ & ~(_062_);
  assign _064_ = _032_ & ~(_063_);
  assign _065_ = \dpath.a_lt_b$in1 [1] | \dpath.a_lt_b$in1 [0];
  assign _066_ = \dpath.a_lt_b$in1 [3] | \dpath.a_lt_b$in1 [2];
  assign _067_ = _066_ | _065_;
  assign _068_ = \dpath.a_lt_b$in1 [5] | \dpath.a_lt_b$in1 [4];
  assign _069_ = \dpath.a_lt_b$in1 [7] | \dpath.a_lt_b$in1 [6];
  assign _070_ = _069_ | _068_;
  assign _071_ = _070_ | _067_;
  assign _072_ = \dpath.a_lt_b$in1 [9] | \dpath.a_lt_b$in1 [8];
  assign _073_ = \dpath.a_lt_b$in1 [11] | \dpath.a_lt_b$in1 [10];
  assign _074_ = _073_ | _072_;
  assign _075_ = \dpath.a_lt_b$in1 [13] | \dpath.a_lt_b$in1 [12];
  assign _076_ = \dpath.a_lt_b$in1 [15] | \dpath.a_lt_b$in1 [14];
  assign _077_ = _076_ | _075_;
  assign _078_ = _077_ | _074_;
  assign _079_ = _078_ | _071_;
  assign _080_ = _079_ | _064_;
  assign _081_ = reset | ~(_080_);
  assign _082_ = \ctrl.state.out [2] & ~(_081_);
  assign _083_ = req_rdy & req_val;
  assign _084_ = reset | ~(_083_);
  assign _085_ = req_rdy & ~(_084_);
  assign _002_ = _085_ | _082_;
  assign _087_ = \ctrl.state.out [2] | ~(\ctrl.state.out [1]);
  assign resp_val = _086_ & ~(_087_);
  assign _088_ = resp_val & resp_rdy;
  assign _089_ = reset | ~(_088_);
  assign _090_ = \ctrl.state.out [1] & ~(_089_);
  assign _091_ = _090_ | reset;
  assign _092_ = _083_ | reset;
  assign _093_ = req_rdy & ~(_092_);
  assign _000_ = _093_ | _091_;
  assign _094_ = _080_ | reset;
  assign _095_ = \ctrl.state.out [2] & ~(_094_);
  assign _096_ = _088_ | reset;
  assign _097_ = \ctrl.state.out [1] & ~(_096_);
  assign _001_ = _097_ | _095_;
  assign \dpath.b_mux$out [0] = _086_ ? \dpath.a_lt_b$in0 [0] : req_msg[0];
  assign \dpath.b_mux$out [1] = _086_ ? \dpath.a_lt_b$in0 [1] : req_msg[1];
  assign \dpath.b_mux$out [2] = _086_ ? \dpath.a_lt_b$in0 [2] : req_msg[2];
  assign \dpath.b_mux$out [3] = _086_ ? \dpath.a_lt_b$in0 [3] : req_msg[3];
  assign \dpath.b_mux$out [4] = _086_ ? \dpath.a_lt_b$in0 [4] : req_msg[4];
  assign \dpath.b_mux$out [5] = _086_ ? \dpath.a_lt_b$in0 [5] : req_msg[5];
  assign \dpath.b_mux$out [6] = _086_ ? \dpath.a_lt_b$in0 [6] : req_msg[6];
  assign \dpath.b_mux$out [7] = _086_ ? \dpath.a_lt_b$in0 [7] : req_msg[7];
  assign \dpath.b_mux$out [8] = _086_ ? \dpath.a_lt_b$in0 [8] : req_msg[8];
  assign \dpath.b_mux$out [9] = _086_ ? \dpath.a_lt_b$in0 [9] : req_msg[9];
  assign \dpath.b_mux$out [10] = _086_ ? \dpath.a_lt_b$in0 [10] : req_msg[10];
  assign \dpath.b_mux$out [11] = _086_ ? \dpath.a_lt_b$in0 [11] : req_msg[11];
  assign \dpath.b_mux$out [12] = _086_ ? \dpath.a_lt_b$in0 [12] : req_msg[12];
  assign \dpath.b_mux$out [13] = _086_ ? \dpath.a_lt_b$in0 [13] : req_msg[13];
  assign \dpath.b_mux$out [14] = _086_ ? \dpath.a_lt_b$in0 [14] : req_msg[14];
  assign \dpath.b_mux$out [15] = _086_ ? \dpath.a_lt_b$in0 [15] : req_msg[15];
  assign _098_ = req_rdy | ~(\ctrl.state.out [2]);
  assign _099_ = _064_ | ~(\ctrl.state.out [2]);
  assign _100_ = _086_ & ~(_099_);
  assign _101_ = ~(_064_ & \ctrl.state.out [2]);
  assign _102_ = _086_ & ~(_101_);
  assign _103_ = _100_ | ~(_102_);
  assign _104_ = \dpath.a_lt_b$in1 [0] & ~(_103_);
  assign _105_ = _100_ & ~(_102_);
  assign _106_ = _105_ & resp_msg[0];
  assign _107_ = _106_ | _104_;
  assign \dpath.a_mux$out [0] = _098_ ? req_msg[16] : _107_;
  assign _108_ = \dpath.a_lt_b$in1 [1] & ~(_103_);
  assign _110_ = _105_ & ~(_109_);
  assign _111_ = _110_ | _108_;
  assign \dpath.a_mux$out [1] = _098_ ? req_msg[17] : _111_;
  assign _237_ = ~clk;
  assign \dpath.a_lt_b$in0 [15] = ~_182_;
  assign \dpath.a_lt_b$in0 [14] = ~_183_;
  assign \dpath.a_lt_b$in0 [13] = ~_184_;
  assign \dpath.a_lt_b$in0 [12] = ~_185_;
  assign \dpath.a_lt_b$in0 [11] = ~_186_;
  assign \dpath.a_lt_b$in0 [10] = ~_187_;
  assign \dpath.a_lt_b$in0 [9] = ~_188_;
  assign \dpath.a_lt_b$in0 [8] = ~_189_;
  assign \dpath.a_lt_b$in0 [7] = ~_190_;
  assign \dpath.a_lt_b$in0 [6] = ~_191_;
  assign \dpath.a_lt_b$in0 [5] = ~_192_;
  assign \dpath.a_lt_b$in0 [4] = ~_193_;
  assign \dpath.a_lt_b$in0 [3] = ~_194_;
  assign \dpath.a_lt_b$in0 [2] = ~_195_;
  assign \dpath.a_lt_b$in0 [1] = ~_196_;
  assign \dpath.a_lt_b$in0 [0] = ~_216_;
  assign \dpath.a_lt_b$in1 [15] = ~_217_;
  assign \dpath.a_lt_b$in1 [14] = ~_213_;
  assign \dpath.a_lt_b$in1 [13] = ~_220_;
  assign \dpath.a_lt_b$in1 [12] = ~_210_;
  assign \dpath.a_lt_b$in1 [11] = ~_223_;
  assign \dpath.a_lt_b$in1 [10] = ~_209_;
  assign \dpath.a_lt_b$in1 [9] = ~_226_;
  assign \dpath.a_lt_b$in1 [8] = ~_207_;
  assign \dpath.a_lt_b$in1 [7] = ~_228_;
  assign \dpath.a_lt_b$in1 [6] = ~_205_;
  assign \dpath.a_lt_b$in1 [5] = ~_231_;
  assign \dpath.a_lt_b$in1 [4] = ~_203_;
  assign \dpath.a_lt_b$in1 [3] = ~_234_;
  assign \dpath.a_lt_b$in1 [2] = ~_201_;
  assign \dpath.a_lt_b$in1 [1] = ~_215_;
  assign \dpath.a_lt_b$in1 [0] = ~_197_;
  assign \ctrl.state.out [2] = ~_198_;
  assign \ctrl.state.out [1] = ~_199_;
  assign req_rdy = ~_086_;
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:44.26-46.12" *)
  FAx1_ASAP7_75t_R _491_ (
    .A(_200_),
    .B(_201_),
    .CI(\dpath.a_lt_b$in0 [2]),
    .CON(_117_),
    .SN(_113_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:44.26-46.12" *)
  FAx1_ASAP7_75t_R _492_ (
    .A(_202_),
    .B(_203_),
    .CI(\dpath.a_lt_b$in0 [4]),
    .CON(_126_),
    .SN(_122_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:44.26-46.12" *)
  FAx1_ASAP7_75t_R _493_ (
    .A(_204_),
    .B(_205_),
    .CI(\dpath.a_lt_b$in0 [6]),
    .CON(_137_),
    .SN(_133_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:44.26-46.12" *)
  FAx1_ASAP7_75t_R _494_ (
    .A(_206_),
    .B(_207_),
    .CI(\dpath.a_lt_b$in0 [8]),
    .CON(_146_),
    .SN(_142_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:44.26-46.12" *)
  FAx1_ASAP7_75t_R _495_ (
    .A(_208_),
    .B(_209_),
    .CI(\dpath.a_lt_b$in0 [10]),
    .CON(_157_),
    .SN(_153_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:44.26-46.12" *)
  FAx1_ASAP7_75t_R _496_ (
    .A(_210_),
    .B(\dpath.a_lt_b$in0 [12]),
    .CI(_211_),
    .CON(_168_),
    .SN(_164_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:44.26-46.12" *)
  FAx1_ASAP7_75t_R _497_ (
    .A(_212_),
    .B(_213_),
    .CI(\dpath.a_lt_b$in0 [14]),
    .CON(_179_),
    .SN(_175_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:44.26-46.12" *)
  FAx1_ASAP7_75t_R _498_ (
    .A(_214_),
    .B(_215_),
    .CI(\dpath.a_lt_b$in0 [1]),
    .CON(_058_),
    .SN(_109_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:20.29-24.14" *)
  HAxp5_ASAP7_75t_R _499_ (
    .A(\dpath.a_lt_b$in1 [0]),
    .B(_216_),
    .CON(_214_),
    .SN(resp_msg[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:20.29-24.14" *)
  HAxp5_ASAP7_75t_R _500_ (
    .A(_217_),
    .B(\dpath.a_lt_b$in0 [15]),
    .CON(_218_),
    .SN(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:20.29-24.14" *)
  HAxp5_ASAP7_75t_R _501_ (
    .A(_213_),
    .B(\dpath.a_lt_b$in0 [14]),
    .CON(_004_),
    .SN(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:20.29-24.14" *)
  HAxp5_ASAP7_75t_R _502_ (
    .A(_220_),
    .B(\dpath.a_lt_b$in0 [13]),
    .CON(_009_),
    .SN(_221_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:20.29-24.14" *)
  HAxp5_ASAP7_75t_R _503_ (
    .A(_210_),
    .B(\dpath.a_lt_b$in0 [12]),
    .CON(_010_),
    .SN(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:20.29-24.14" *)
  HAxp5_ASAP7_75t_R _504_ (
    .A(_223_),
    .B(\dpath.a_lt_b$in0 [11]),
    .CON(_018_),
    .SN(_224_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:20.29-24.14" *)
  HAxp5_ASAP7_75t_R _505_ (
    .A(_209_),
    .B(\dpath.a_lt_b$in0 [10]),
    .CON(_019_),
    .SN(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:20.29-24.14" *)
  HAxp5_ASAP7_75t_R _506_ (
    .A(_226_),
    .B(\dpath.a_lt_b$in0 [9]),
    .CON(_024_),
    .SN(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:20.29-24.14" *)
  HAxp5_ASAP7_75t_R _507_ (
    .A(_207_),
    .B(\dpath.a_lt_b$in0 [8]),
    .CON(_026_),
    .SN(_033_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:20.29-24.14" *)
  HAxp5_ASAP7_75t_R _508_ (
    .A(_228_),
    .B(\dpath.a_lt_b$in0 [7]),
    .CON(_037_),
    .SN(_229_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:20.29-24.14" *)
  HAxp5_ASAP7_75t_R _509_ (
    .A(_205_),
    .B(\dpath.a_lt_b$in0 [6]),
    .CON(_038_),
    .SN(_041_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:20.29-24.14" *)
  HAxp5_ASAP7_75t_R _510_ (
    .A(_231_),
    .B(\dpath.a_lt_b$in0 [5]),
    .CON(_043_),
    .SN(_232_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:20.29-24.14" *)
  HAxp5_ASAP7_75t_R _511_ (
    .A(_203_),
    .B(\dpath.a_lt_b$in0 [4]),
    .CON(_044_),
    .SN(_049_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:20.29-24.14" *)
  HAxp5_ASAP7_75t_R _512_ (
    .A(_234_),
    .B(\dpath.a_lt_b$in0 [3]),
    .CON(_052_),
    .SN(_235_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./platforms/asap7/yoSys/cells_adders_R.v:20.29-24.14" *)
  HAxp5_ASAP7_75t_R _513_ (
    .A(_201_),
    .B(\dpath.a_lt_b$in0 [2]),
    .CON(_053_),
    .SN(_056_)
  );
  assign _202_ = ~_060_;
  assign _204_ = ~_132_;
  assign _211_ = ~_163_;
  assign _206_ = ~_062_;
  assign _208_ = ~_152_;
  assign _212_ = ~_174_;
  DFFLQNx1_ASAP7_75t_R _520_ (
    .CLK(_237_),
    .D(_000_),
    .QN(_086_)
  );
  DFFLQNx1_ASAP7_75t_R _521_ (
    .CLK(_237_),
    .D(_001_),
    .QN(_199_)
  );
  DFFLQNx1_ASAP7_75t_R _522_ (
    .CLK(_237_),
    .D(_002_),
    .QN(_198_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:496.28-503.4" *)
  DFFLQNx1_ASAP7_75t_R _523_ (
    .CLK(_237_),
    .D(_238_),
    .QN(_197_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:496.28-503.4" *)
  DFFLQNx1_ASAP7_75t_R _524_ (
    .CLK(_237_),
    .D(_239_),
    .QN(_215_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:496.28-503.4" *)
  DFFLQNx1_ASAP7_75t_R _525_ (
    .CLK(_237_),
    .D(_240_),
    .QN(_201_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:496.28-503.4" *)
  DFFLQNx1_ASAP7_75t_R _526_ (
    .CLK(_237_),
    .D(_241_),
    .QN(_234_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:496.28-503.4" *)
  DFFLQNx1_ASAP7_75t_R _527_ (
    .CLK(_237_),
    .D(_242_),
    .QN(_203_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:496.28-503.4" *)
  DFFLQNx1_ASAP7_75t_R _528_ (
    .CLK(_237_),
    .D(_243_),
    .QN(_231_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:496.28-503.4" *)
  DFFLQNx1_ASAP7_75t_R _529_ (
    .CLK(_237_),
    .D(_244_),
    .QN(_205_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:496.28-503.4" *)
  DFFLQNx1_ASAP7_75t_R _530_ (
    .CLK(_237_),
    .D(_245_),
    .QN(_228_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:496.28-503.4" *)
  DFFLQNx1_ASAP7_75t_R _531_ (
    .CLK(_237_),
    .D(_246_),
    .QN(_207_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:496.28-503.4" *)
  DFFLQNx1_ASAP7_75t_R _532_ (
    .CLK(_237_),
    .D(_247_),
    .QN(_226_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:496.28-503.4" *)
  DFFLQNx1_ASAP7_75t_R _533_ (
    .CLK(_237_),
    .D(_248_),
    .QN(_209_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:496.28-503.4" *)
  DFFLQNx1_ASAP7_75t_R _534_ (
    .CLK(_237_),
    .D(_249_),
    .QN(_223_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:496.28-503.4" *)
  DFFLQNx1_ASAP7_75t_R _535_ (
    .CLK(_237_),
    .D(_250_),
    .QN(_210_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:496.28-503.4" *)
  DFFLQNx1_ASAP7_75t_R _536_ (
    .CLK(_237_),
    .D(_251_),
    .QN(_220_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:496.28-503.4" *)
  DFFLQNx1_ASAP7_75t_R _537_ (
    .CLK(_237_),
    .D(_252_),
    .QN(_213_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:496.28-503.4" *)
  DFFLQNx1_ASAP7_75t_R _538_ (
    .CLK(_237_),
    .D(_253_),
    .QN(_217_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:396.28-403.4" *)
  DFFLQNx1_ASAP7_75t_R _539_ (
    .CLK(_237_),
    .D(_254_),
    .QN(_216_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:396.28-403.4" *)
  DFFLQNx1_ASAP7_75t_R _540_ (
    .CLK(_237_),
    .D(_255_),
    .QN(_196_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:396.28-403.4" *)
  DFFLQNx1_ASAP7_75t_R _541_ (
    .CLK(_237_),
    .D(_256_),
    .QN(_195_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:396.28-403.4" *)
  DFFLQNx1_ASAP7_75t_R _542_ (
    .CLK(_237_),
    .D(_257_),
    .QN(_194_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:396.28-403.4" *)
  DFFLQNx1_ASAP7_75t_R _543_ (
    .CLK(_237_),
    .D(_258_),
    .QN(_193_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:396.28-403.4" *)
  DFFLQNx1_ASAP7_75t_R _544_ (
    .CLK(_237_),
    .D(_259_),
    .QN(_192_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:396.28-403.4" *)
  DFFLQNx1_ASAP7_75t_R _545_ (
    .CLK(_237_),
    .D(_260_),
    .QN(_191_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:396.28-403.4" *)
  DFFLQNx1_ASAP7_75t_R _546_ (
    .CLK(_237_),
    .D(_261_),
    .QN(_190_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:396.28-403.4" *)
  DFFLQNx1_ASAP7_75t_R _547_ (
    .CLK(_237_),
    .D(_262_),
    .QN(_189_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:396.28-403.4" *)
  DFFLQNx1_ASAP7_75t_R _548_ (
    .CLK(_237_),
    .D(_263_),
    .QN(_188_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:396.28-403.4" *)
  DFFLQNx1_ASAP7_75t_R _549_ (
    .CLK(_237_),
    .D(_264_),
    .QN(_187_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:396.28-403.4" *)
  DFFLQNx1_ASAP7_75t_R _550_ (
    .CLK(_237_),
    .D(_265_),
    .QN(_186_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:396.28-403.4" *)
  DFFLQNx1_ASAP7_75t_R _551_ (
    .CLK(_237_),
    .D(_266_),
    .QN(_185_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:396.28-403.4" *)
  DFFLQNx1_ASAP7_75t_R _552_ (
    .CLK(_237_),
    .D(_267_),
    .QN(_184_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:396.28-403.4" *)
  DFFLQNx1_ASAP7_75t_R _553_ (
    .CLK(_237_),
    .D(_268_),
    .QN(_183_)
  );
  (* src = "./designs/src/gcd/gcd.v:66.38-79.4|./designs/src/gcd/gcd.v:571.3-577.6|./designs/src/gcd/gcd.v:396.28-403.4" *)
  DFFLQNx1_ASAP7_75t_R _554_ (
    .CLK(_237_),
    .D(_269_),
    .QN(_182_)
  );
  assign _238_ = \ctrl.b_reg_en  ? \dpath.b_mux$out [0] : \dpath.a_lt_b$in1 [0];
  assign _239_ = \ctrl.b_reg_en  ? \dpath.b_mux$out [1] : \dpath.a_lt_b$in1 [1];
  assign _240_ = \ctrl.b_reg_en  ? \dpath.b_mux$out [2] : \dpath.a_lt_b$in1 [2];
  assign _241_ = \ctrl.b_reg_en  ? \dpath.b_mux$out [3] : \dpath.a_lt_b$in1 [3];
  assign _242_ = \ctrl.b_reg_en  ? \dpath.b_mux$out [4] : \dpath.a_lt_b$in1 [4];
  assign _243_ = \ctrl.b_reg_en  ? \dpath.b_mux$out [5] : \dpath.a_lt_b$in1 [5];
  assign _244_ = \ctrl.b_reg_en  ? \dpath.b_mux$out [6] : \dpath.a_lt_b$in1 [6];
  assign _245_ = \ctrl.b_reg_en  ? \dpath.b_mux$out [7] : \dpath.a_lt_b$in1 [7];
  assign _246_ = \ctrl.b_reg_en  ? \dpath.b_mux$out [8] : \dpath.a_lt_b$in1 [8];
  assign _247_ = \ctrl.b_reg_en  ? \dpath.b_mux$out [9] : \dpath.a_lt_b$in1 [9];
  assign _248_ = \ctrl.b_reg_en  ? \dpath.b_mux$out [10] : \dpath.a_lt_b$in1 [10];
  assign _249_ = \ctrl.b_reg_en  ? \dpath.b_mux$out [11] : \dpath.a_lt_b$in1 [11];
  assign _250_ = \ctrl.b_reg_en  ? \dpath.b_mux$out [12] : \dpath.a_lt_b$in1 [12];
  assign _251_ = \ctrl.b_reg_en  ? \dpath.b_mux$out [13] : \dpath.a_lt_b$in1 [13];
  assign _252_ = \ctrl.b_reg_en  ? \dpath.b_mux$out [14] : \dpath.a_lt_b$in1 [14];
  assign _253_ = \ctrl.b_reg_en  ? \dpath.b_mux$out [15] : \dpath.a_lt_b$in1 [15];
  assign _254_ = \ctrl.a_reg_en  ? \dpath.a_mux$out [0] : \dpath.a_lt_b$in0 [0];
  assign _255_ = \ctrl.a_reg_en  ? \dpath.a_mux$out [1] : \dpath.a_lt_b$in0 [1];
  assign _256_ = \ctrl.a_reg_en  ? \dpath.a_mux$out [2] : \dpath.a_lt_b$in0 [2];
  assign _257_ = \ctrl.a_reg_en  ? \dpath.a_mux$out [3] : \dpath.a_lt_b$in0 [3];
  assign _258_ = \ctrl.a_reg_en  ? \dpath.a_mux$out [4] : \dpath.a_lt_b$in0 [4];
  assign _259_ = \ctrl.a_reg_en  ? \dpath.a_mux$out [5] : \dpath.a_lt_b$in0 [5];
  assign _260_ = \ctrl.a_reg_en  ? \dpath.a_mux$out [6] : \dpath.a_lt_b$in0 [6];
  assign _261_ = \ctrl.a_reg_en  ? \dpath.a_mux$out [7] : \dpath.a_lt_b$in0 [7];
  assign _262_ = \ctrl.a_reg_en  ? \dpath.a_mux$out [8] : \dpath.a_lt_b$in0 [8];
  assign _263_ = \ctrl.a_reg_en  ? \dpath.a_mux$out [9] : \dpath.a_lt_b$in0 [9];
  assign _264_ = \ctrl.a_reg_en  ? \dpath.a_mux$out [10] : \dpath.a_lt_b$in0 [10];
  assign _265_ = \ctrl.a_reg_en  ? \dpath.a_mux$out [11] : \dpath.a_lt_b$in0 [11];
  assign _266_ = \ctrl.a_reg_en  ? \dpath.a_mux$out [12] : \dpath.a_lt_b$in0 [12];
  assign _267_ = \ctrl.a_reg_en  ? \dpath.a_mux$out [13] : \dpath.a_lt_b$in0 [13];
  assign _268_ = \ctrl.a_reg_en  ? \dpath.a_mux$out [14] : \dpath.a_lt_b$in0 [14];
  assign _269_ = \ctrl.a_reg_en  ? \dpath.a_mux$out [15] : \dpath.a_lt_b$in0 [15];
  assign resp_msg[10] = ~(* src = "./platforms/asap7/yoSys/cells_adders_R.v:50.21-50.27" *) _153_;
  assign resp_msg[14] = ~(* src = "./platforms/asap7/yoSys/cells_adders_R.v:50.21-50.27" *) _175_;
  assign _222_ = ~(* src = "./platforms/asap7/yoSys/cells_adders_R.v:50.21-50.27" *) _221_;
  assign resp_msg[6] = ~(* src = "./platforms/asap7/yoSys/cells_adders_R.v:50.21-50.27" *) _133_;
  assign _236_ = ~(* src = "./platforms/asap7/yoSys/cells_adders_R.v:50.21-50.27" *) _235_;
  assign resp_msg[4] = ~(* src = "./platforms/asap7/yoSys/cells_adders_R.v:50.21-50.27" *) _122_;
  assign _233_ = ~(* src = "./platforms/asap7/yoSys/cells_adders_R.v:50.21-50.27" *) _232_;
  assign resp_msg[2] = ~(* src = "./platforms/asap7/yoSys/cells_adders_R.v:50.21-50.27" *) _113_;
  assign _230_ = ~(* src = "./platforms/asap7/yoSys/cells_adders_R.v:50.21-50.27" *) _229_;
  assign _227_ = ~(* src = "./platforms/asap7/yoSys/cells_adders_R.v:50.21-50.27" *) _025_;
  assign _219_ = ~(* src = "./platforms/asap7/yoSys/cells_adders_R.v:49.21-49.27" *) _218_;
  assign resp_msg[1] = ~(* src = "./platforms/asap7/yoSys/cells_adders_R.v:50.21-50.27" *) _109_;
  assign _200_ = ~(* src = "./platforms/asap7/yoSys/cells_adders_R.v:49.21-49.27" *) _058_;
  assign resp_msg[8] = ~(* src = "./platforms/asap7/yoSys/cells_adders_R.v:50.21-50.27" *) _142_;
  assign resp_msg[12] = ~(* src = "./platforms/asap7/yoSys/cells_adders_R.v:50.21-50.27" *) _164_;
  assign _225_ = ~(* src = "./platforms/asap7/yoSys/cells_adders_R.v:50.21-50.27" *) _224_;
  assign \ctrl.state.out [0] = req_rdy;
endmodule
